// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadAuthToken(arg1) {
  return window['go']['main']['App']['LoadAuthToken'](arg1);
}

export function RemoveAuthToken(arg1) {
  return window['go']['main']['App']['RemoveAuthToken'](arg1);
}

export function SaveAuthToken(arg1, arg2) {
  return window['go']['main']['App']['SaveAuthToken'](arg1, arg2);
}

export function VerifyHostKey(arg1) {
  return window['go']['main']['App']['VerifyHostKey'](arg1);
}
