// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Alert(arg1:string):Promise<void>;

export function Confirm(arg1:string):Promise<boolean>;

export function GetHosts():Promise<Array<main.Host>>;

export function Greet(arg1:string):Promise<string>;

export function LoadAuthToken(arg1:string):Promise<string>;

export function RemoveAuthToken(arg1:string):Promise<void>;

export function SaveAuthToken(arg1:string,arg2:string):Promise<void>;

export function VerifyHostKey(arg1:string):Promise<string>;
