// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1) {
  return window['go']['main']['App']['Alert'](arg1);
}

export function Confirm(arg1) {
  return window['go']['main']['App']['Confirm'](arg1);
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadAuthToken() {
  return window['go']['main']['App']['LoadAuthToken']();
}

export function RemoveAuthToken() {
  return window['go']['main']['App']['RemoveAuthToken']();
}

export function SaveAuthToken(arg1) {
  return window['go']['main']['App']['SaveAuthToken'](arg1);
}

export function VerifyHostKey(arg1) {
  return window['go']['main']['App']['VerifyHostKey'](arg1);
}
