// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function VerifyHostKey(arg1) {
  return window['go']['main']['App']['VerifyHostKey'](arg1);
}
